### PR TITLE
Updates on NatsServerRunner

### PR DESCRIPTION
**Pull request by umutsahin**
* Added wait before connect and 3 retrials
* Added cause to thrown exception

### CODE REVIEW

**Comment by scottf** [comment]
@umutsahin I'm okay with the idea behind this, but I would prefer to make the changes to the second loop optional. We use this heavily in the java client unit tests and have never had a problem. Maybe you can give some details on why you offered the change?

And for optional, b/c I don't want to change the signatures, it might need to be done the way I hacked the logging level. I will also consider doing a major version release or maybe a second set of entry points.

**Comment by umutsahin** [comment]
Hi @scottf,
With latest nats-server (2.9.10) on macOS and linux I see this issue, usually it is not able to connect on the first trial.
I can move the sleep after socket connect, what do you think ?

**Comment by umutsahin** [comment]
Moved sleep into catch block @scottf

**Comment by scottf** [comment]
Changes have been incorporated here: https://github.com/nats-io/java-nats-server-runner/pull/23

**Pull request closed without merging**
